Update edit locale page to authflowv2
cychiuae/authgear-server pull request #2
Opened 2024-08-29 10:34 UTC by Kuixz

For some reason this PR has two of your commits also. 
Normally would add a ref (#) to the PR this is based on. But I think this is just based on one of your branch. So not sure. :doglaugh:

2024-08-30 02:09 UTC, Kuixz commented
What is this CI :(

2024-08-30 02:11 UTC, Kuixz commented
When navigating Settings -> Edit Profile -> Preferred Language -> Reload page -> Back arrow -> Back arrow

The styles have changed and the icons became blue.
Do you know why? @yyorkchan

2024-08-30 02:54 UTC, yyorkchan commented
@Kuixz It is an expected behaviour when navigating between V1 And V2 page due to the turbo framework. It won't be happening when we complete all pages as V2 version. No worries!

2024-09-03 06:26 UTC, cychiuae requested changes

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/settings_profile_edit_locale.html
> +{{ template "authflowv2/__html_head.html" . }}
We don't need it. It is already in `authflowv2/__settings_page_frame.html`

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/settings_profile_edit_locale.html
> +)
1. Identation
2. Missing the title for back button

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/settings_profile_edit_locale.html
> +method="post">
Identation

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +{{ end }}
Please add a newline at the end of this file

https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +    {{ if $.InputAttrs }}{{ htmlattr $.InputAttrs }}{{ end }}
Indentation

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +    Late apply class="hidden" during connect() in localeInput.ts for noscript -->
This comment was from other developer and it is not related to your work.

Please try not to just copy & paste. You need to think about what you are going to paste.

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +            data-action="click->custom-select#close"
Indentation

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +            <i class="material-icons">close</i>
Indentation

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +        </li>
Indentation

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +        </li>
Indentation

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +                placeholder="{{ translate "v2.component.locale-input.default.search-label" . }}"
This will not work because `translate` will wrap the translation in a span tag. Here we just want to have the text only. Please change to use `include` instead

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +]"
indentation

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +data-custom-select-options-value="[         {{/* TODO: Please take a careful look at the Not provided span over here ↓ */}}
I am not so sure what you are doing here.

2024-09-03 06:26 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/__locale_input.html
> +        data-custom-select-target="options"
indentation

2024-09-03 06:32 UTC, cychiuae commented
Let me take over this PR

2024-09-03 08:10 UTC, merged