Add view email page for authflow v2 (PR v2)
cychiuae/authgear-server pull request #29
Opened 2024-09-13 09:22 UTC by Kuixz

Requires #20: remove email identity

Because #23 merged already, I rebased on top of the most recent feat-authuiv2-settings (13/9 at 2:17). As a result this PR has a copy of the commits in #27 and need to be rebased again after #27 merged.

2024-09-13 10:14 UTC, Kuixz commented
There is an issue:
The back button leads to `settings/identity/email` without `q_login_id_key` field. Users may see more emails than expected after editing / viewing an email.

Is there any better way to avoid this than to pass q_login_id_key in to the view email page?

2024-09-16 03:09 UTC, cychiuae requested changes

2024-09-16 03:09 UTC, cychiuae commented on pkg/auth/handler/webapp/authflowv2/routes.go
> +	AuthflowV2RouteSettingsIdentityViewEmail = "/settings/identity/view-email"
AuthUI convention is using understore so please change it to `view_email`

2024-09-16 03:09 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/settings_identity_view_email.html
> +{{ end }}
Add newline charactor at the end

2024-09-16 03:09 UTC, cychiuae commented on pkg/auth/handler/webapp/authflowv2/settings_identity_view_email.go
> +	}
You can just use `h.Identities.LoginID.Get(*userID, loginID)`

2024-09-16 03:09 UTC, cychiuae commented on pkg/auth/handler/webapp/authflowv2/settings_identity_view_email.go
> +	deleteDisabled := len(identities) < 2 // Do not let user remove their last identity
Here is not correct because users can have other types of identity other than login id identity, e.g. ldap, oauth etc..
I think you don't need to handle this. Just default deleteDisabled is true is fine.

2024-09-16 03:09 UTC, cychiuae commented on pkg/auth/handler/webapp/authflowv2/settings_identity_view_email.go
> +	EmailIdentity  identity.LoginID
The type should be `*identity.LoginID` to match other places' usage

2024-09-16 03:09 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/settings_identity_view_email.html
> +{{ $LoginIDKey := $.EmailIdentity.ID }}
It is not `LoginIDKey`. It is identity ID. Don't mix them up

2024-09-16 03:09 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/settings_identity_view_email.html
> +    {{ $RemoveDialogID := "removeDialog" }}
The dialog ID should be more specific. Please use something like `remove-email-identity-dialog` instead.

2024-09-16 03:09 UTC, cychiuae commented on resources/authgear/templates/en/web/authflowv2/settings_identity_view_email.html
> +  <span style="word-break: break-all;">{{ $.Text }}</span>
What is this?

- Your template name should be more "scoped" because template names are global. If you dont be remo specific, you will collide with other template or affect other template

2024-09-16 03:09 UTC, cychiuae commented on resources/authgear/templates/en/translation.json
> +  "v2.page.settings-identity-view-email.remove.title": "Remove Email Address",
`v2.page.settings-identity-view-email.default.remove-identity-dialog-title`

2024-09-16 03:09 UTC, cychiuae commented on resources/authgear/templates/en/translation.json
> +  "v2.page.settings-identity-view-email.remove.description": "Are you sure you want to remove the email address <b>{target}</b> from your account?",
`v2.page.settings-identity-view-email.default.remove-identity-dialog-description`

2024-09-16 03:09 UTC, cychiuae commented on pkg/auth/handler/webapp/authflowv2/settings_identity_view_email.go
> +		}
1. Define a json schema for remove from
2. Put the identity id in the form as a hidden input instead of getting from query string

2024-09-16 06:08 UTC, Kuixz commented
All changes have been made @cychiuae

2024-09-17 03:51 UTC, Kuixz commented
Please tell me if/when this is merged because format changes need to propagate across the other prs (need to remove `inline_breakable` from a few places.) @cychiuae

2024-09-20 04:27 UTC, merged